name: Continuous Integration

on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * 1'

defaults:
  run:
    # This is needed for miniconda, see:
    # https://github.com/marketplace/actions/setup-miniconda#important.
    shell: bash -l {0}

jobs:
  pytest-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - sanity-snakemake
          - sanity-snakemake-lint
          - sanity-singularity
          - dry-run-vanilla
          - dry-run-two-bamfiles
          - dry-run-minimal
          - dry-run-reference-only
          - dry-run-genes-only
          - dry-run-p_utg
          - dry-run-p_ctg
          - integration-vanilla
          - integration-two-bamfiles
          - integration-reference-only
          - integration-genes-only
    steps:
    - uses: actions/checkout@v2

    - uses: eWaterCycle/setup-singularity@v6
      with:
        singularity-version: 3.6.4

    - uses: conda-incubator/setup-miniconda@v2.0.1
      # https://github.com/conda-incubator/setup-miniconda.
      with:
        activate-environment: HiFi-assembly
        environment-file: environment.yml
        auto-activate-base: false

    - name: Run test in conda evironment
      run: >-
        pytest --keep-workflow-wd-on-fail --tag ${{ matrix.test }}

    - name: Check job stderr messages in case of failure
      if: ${{ failure() }}
      run: >-
        bash -c '
        for file in $(find /tmp/pytest_workflow_* -name log.err); do
          echo $file; cat $file
        done
        '
    - name: Check job stdout messages in case of failure
      if: ${{ failure() }}
      run: >-
        bash -c '
        for file in $(find /tmp/pytest_workflow_* -name log.out); do
          echo $file; cat $file
        done
        '
    - name: Check pipline log files in case of failure
      if: ${{ failure() }}
      run: >-
        bash -c '
        for file in $(find /tmp/pytest_workflow_*/*/log/ -type f); do
          echo $file; cat $file
        done
        '

  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.0.1
      # https://github.com/conda-incubator/setup-miniconda.
      with:
        activate-environment: HiFi-assembly
        environment-file: environment.yml
        auto-activate-base: false
    - name: Run pytest for padding
      run: pytest scripts/test_padding.py
